# you will use this password to log in to Grafana
# change the adminPassword value to your desired password
adminPassword: kaldi-test-password
# override the datasource search value and use our own datasource
sidecar:
  datasources:
    enabled: true
    label: grafana_datasource
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    kaldi-custom-dashboard:
      file: dashboards/kaldi-grafana-dashboard.json
    kubernetes-cluster:
      # adding another good dashboard template
      # gnetId: 6417
      gnetId: 315
      revision: 1
      datasource: Prometheus